/**
 * The `openmaic_widget` toolview: renders a complete OpenMAIC widget document
 * (generated by @openmaic/generation) inside `<iframe sandbox="allow-scripts">`.
 * Unlike the fragment card, a widget is a full HTML document with its own
 * head, KaTeX/Tailwind CDN references, and inline scripts, so it is mounted as
 * `srcdoc` verbatim rather than wrapped in the fragment skeleton.
 *
 * The inline card auto-sizes up to a cap and carries an expand button that
 * opens the same widget in a large overlay, since simulations and games need
 * more viewport than the conversation column gives them.
 *
 * @module @openmaic/dsh-openmaic/client/WidgetCard
 */

import { useEffect, useState, type CSSProperties } from 'react'
import type { ToolCallViewProps } from '@deepseek-ai/dsh-client-ui-tool/client'
import { widgetMetaFrom, type WidgetMeta } from '../widget-meta.ts'
import { buildWidgetDoc, HEIGHT_MESSAGE_TYPE } from './shell.ts'

const MIN_HEIGHT = 480
const HEIGHT_CAP = 1600

const headerStyle: CSSProperties = {
  display: 'flex',
  alignItems: 'baseline',
  gap: 8,
  fontSize: 12,
  opacity: 0.65,
  margin: '2px 0 6px',
  overflow: 'hidden',
  whiteSpace: 'nowrap',
}

const frameStyle: CSSProperties = {
  display: 'block',
  width: '100%',
  border: 0,
  background: 'transparent',
  colorScheme: 'normal',
}

const expandBtnStyle: CSSProperties = {
  appearance: 'none',
  marginLeft: 'auto',
  border: '1px solid var(--dsw-alias-border-l2, rgba(0 0 0 / 15%))',
  borderRadius: 6,
  padding: '1px 8px',
  background: 'transparent',
  color: 'inherit',
  fontSize: 12,
  cursor: 'pointer',
}

const overlayStyle: CSSProperties = {
  position: 'fixed',
  inset: 0,
  zIndex: 1000,
  display: 'flex',
  flexDirection: 'column',
  background: 'var(--dsw-alias-bg-layer-1, rgba(13 13 13 / 96%))',
  color: 'var(--dsw-alias-label-primary, inherit)',
}

const overlayBarStyle: CSSProperties = {
  display: 'flex',
  alignItems: 'center',
  gap: 8,
  padding: '8px 12px',
  fontSize: 14,
  borderBottom: '1px solid var(--dsw-alias-border-l2, rgba(255 255 255 / 12%))',
}

const overlayFrameStyle: CSSProperties = {
  flex: 1,
  width: '100%',
  border: 0,
  background: 'transparent',
}

const closeBtnStyle: CSSProperties = {
  appearance: 'none',
  marginLeft: 'auto',
  border: '1px solid var(--dsw-alias-border-l2, rgba(255 255 255 / 15%))',
  borderRadius: 6,
  padding: '2px 10px',
  background: 'transparent',
  color: 'inherit',
  fontSize: 13,
  cursor: 'pointer',
}

/** First text line of the durable result content, for the error row. */
function firstResultLine(content: readonly { type: string; text?: string }[]): string {
  for (const block of content) {
    if (block.type === 'text' && typeof block.text === 'string' && block.text.length > 0) {
      const newline = block.text.indexOf('\n')
      return newline === -1 ? block.text : block.text.slice(0, newline)
    }
  }
  return 'widget failed'
}

function WidgetFrame({ meta, callId, height }: { meta: WidgetMeta; callId: string; height?: number | string }) {
  const doc = buildWidgetDoc(meta.html, callId)
  return (
    <iframe
      sandbox="allow-scripts"
      referrerPolicy="no-referrer"
      title={meta.title}
      srcDoc={doc}
      style={{ ...frameStyle, ...(height !== undefined ? { height } : {}) }}
    />
  )
}

function Frame({ meta, callId }: { meta: WidgetMeta; callId: string }) {
  const [height, setHeight] = useState(MIN_HEIGHT)
  const [expanded, setExpanded] = useState(false)

  useEffect(() => {
    const onMessage = (event: MessageEvent) => {
      const data: unknown = event.data
      if (typeof data !== 'object' || data === null) return
      const report = data as { type?: unknown; token?: unknown; height?: unknown }
      if (report.type !== HEIGHT_MESSAGE_TYPE || report.token !== callId) return
      if (typeof report.height !== 'number' || !Number.isFinite(report.height)) return
      setHeight(Math.max(MIN_HEIGHT, Math.min(Math.ceil(report.height), HEIGHT_CAP)))
    }
    addEventListener('message', onMessage)
    return () => removeEventListener('message', onMessage)
  }, [callId])

  return (
    <div>
      <div style={headerStyle}>
        <span style={{ fontWeight: 500 }}>{meta.title}</span>
        <span style={{ overflow: 'hidden', textOverflow: 'ellipsis' }}>OpenMAIC · {meta.widgetType}</span>
        <button type="button" style={expandBtnStyle} onClick={() => setExpanded(true)}>⛶ 展开</button>
      </div>
      <WidgetFrame meta={meta} callId={callId} height={height} />
      {expanded ? (
        <div style={overlayStyle}>
          <div style={overlayBarStyle}>
            <span style={{ fontWeight: 500 }}>{meta.title}</span>
            <span style={{ opacity: 0.6 }}>OpenMAIC · {meta.widgetType}</span>
            <button type="button" style={closeBtnStyle} onClick={() => setExpanded(false)}>关闭</button>
          </div>
          <WidgetFrame meta={meta} callId={`${callId}:expanded`} height="calc(100vh - 52px)" />
        </div>
      ) : null}
    </div>
  )
}

/**
 * Keyed toolview for the `openmaic_widget` tool. Running calls and malformed
 * or failed results stay quiet single lines; only a well-formed persisted meta
 * mounts the frame.
 */
export function WidgetCard({ callId, block }: ToolCallViewProps) {
  if (!('kind' in block)) {
    return <div style={headerStyle}>OpenMAIC · generating widget…</div>
  }
  if (block.isError) {
    return <div style={headerStyle}>OpenMAIC · {firstResultLine(block.content)}</div>
  }
  const meta = widgetMetaFrom(block.meta)
  if (meta === undefined) {
    return <div style={headerStyle}>{firstResultLine(block.content)}</div>
  }
  return <Frame meta={meta} callId={callId} />
}
